### ISSUE TITLE
Remove support for `TIMESTAMP WITH LOCAL TIME ZONE`

### ISSUE THREAD

**Issue by kaklakariada** [exasol/virtual-schema-common-document#178]
Data type `TIMESTAMP WITH LOCAL TIME ZONE` does not make sense for document based virtual schemas that don't support time zones at all. So we decided to drop support completely.

```[tasklist]
### Tasks
- [ ] Add note to EDML user guide that only `TIMESTAMP` is supported
- [ ] Add note to changelog that column type changes from `TIMESTAMP WITH LOCAL TIME ZONE` to `TIMESTAMP` after https://github.com/exasol/edml-java/issues/20 was fixed
- [ ] Upgrade to json schema 2.0.0
```
